import Head from 'next/head'
import ImageHolder from '../components/ImageHolder'
import logoIcon from '../public/icons/logo-icon-gradient.svg'
import payrailIcon from '../public/icons/payrail-logo-black.svg'
import { useEffect } from 'react'
import { useRouter } from 'next/router'

export default function Layout({ children, token }) {
    const router = useRouter()

    useEffect(()=>{
        if(token) {
            router.push("/dashboard")
        }
    },[])
    return (
        <div className="">
            <Head>
                <title>Payrail Agency</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className='flex flex-col py-2 '>
                <section className='flex m-auto w-fit min-h-logo-height py-1 px-1 items-center'>
                    <div className=' relative w-[44px] h-[53px]'>
                        <ImageHolder src={logoIcon} />
                    </div>
                    <div className=' relative ml-[10px] w-[109px] h-[37px]'>
                        <ImageHolder src={payrailIcon} />
                    </div>
                </section>
                <div id='container' className='mt-[80.04px] flex flex-col w-[529px] min-h-[555px] border border-border-gray rounded-[48px] m-auto'>
                    {children}
                </div>
                <section className='m-auto mt-[217px] flex self-end font-pushpenny-book text-[16px] font-[400] leading-[20.83px]'>
                    © Angala Financial Technologies Limited. All Rights Reserved.
                </section>
            </div>
        </div>
    )
}
